run:
  timeout: 5m

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 5
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 40
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/instana/testify"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - sloppyReassign
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules
    settings:
      hugeParam:
        sizeThreshold: 100
  tagliatelle:
    case:
      rules:
        json: snake

linters:
  enable-all: true
  disable:
    - gomnd # deprecated
    - execinquery # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - lll
    - dupl
    - wsl
    - nlreturn
    - mnd
    - err113
    - wrapcheck
    - exhaustive
    - exhaustruct
    - testpackage
    - tparallel
    - paralleltest
    - prealloc
    - forcetypeassert
    - gosec
    - maintidx
    - varnamelen

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - "^cmd"
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
    - 'package-comments: should have a package comment'
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
    - path: webhook.go
      text: "(cyclomatic|cognitive) complexity (\\d+) of func `\\(\\*WebHook\\)\\.handleEvents` is high"
    - path: webhook.go
      text: "Function '(ServeHTTP|handleEvents)' has too many statements"
