language: go

go: master

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u honnef.co/go/tools/cmd/{gosimple,staticcheck}

install:
  - make dependencies
