language: go

go:
  - 1.12.x
  - 1.x

notifications:
  email:
    on_success: never
    on_failure: change

env:
  - GO111MODULE=on

before_install:
  # Install linters and misspell
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.17.1
  - golangci-lint --version

install:
  go mod download
